apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: etudiant20-ns
spec:
  type: NodePort
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 8080 
      nodePort: 30020  